'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('curso', [
      // { sigla: "EM01", nome: "Enfermagem (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH19", nome: "M\u00fasica (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH28", nome: "M\u00fasica (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH30", nome: "Artes Visuais (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH31", nome: "Artes Visuais (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH57", nome: "Artes Visuais (EAD - Polo UaB Itacoatiara)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH58", nome: "Artes Visuais (EAD - Polo UaB Santa Isabel do Rio Negro)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH59", nome: "Artes Visuais (EAD - Polo UaB Tef\u00e9)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FG01", nome: "Agronomia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FG02", nome: "Engenharia Florestal (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FG03", nome: "Engenharia de Pesca (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FG04", nome: "Zootecnia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FG05", nome: "Engenharia de Alimentos (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FS01", nome: "Farm\u00e1cia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FD01", nome: "Direito (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FD02", nome: "Direito (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB02", nome: "Educa\u00e7\u00e3o F\u00edsica(Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB06", nome: "Educa\u00e7\u00e3o F\u00edsica - Promo\u00e7\u00e3o em Sa\u00fade e Lazer (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB07", nome: "Educa\u00e7\u00e3o F\u00edsica - Treinamento Esportivo (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB08", nome: "Fisioterapia (Integral)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB16", nome: "Educa\u00e7\u00e3o F\u00edsica (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FA01", nome: "Administra\u00e7\u00e3o (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FA02", nome: "Administra\u00e7\u00e3o (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FA03", nome: "Ci\u00eancias Cont\u00e1beis (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FA04", nome: "Ci\u00eancias Cont\u00e1beis (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FA05", nome: "Ci\u00eancias Econ\u00f4micas (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FA06", nome: "Ci\u00eancias Econ\u00f4micas (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH01", nome: "Biblioteconomia (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH12", nome: "Comunica\u00e7\u00e3o Social - Rela\u00e7\u00f5es P\u00fablicas (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH25", nome: "Arquivologia (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH27", nome: "Comunica\u00e7\u00e3o Social - Jornalismo (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH13", nome: "Letras - L\u00edngua e Literatura Portuguesa (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH15", nome: "Letras - L\u00edngua e Literatura Inglesa (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH16", nome: "Letras - L\u00edngua e Literatura Francesa (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH21", nome: "Letras - L\u00edngua e Literatura Espanhola (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH23", nome: "Letras - L\u00edngua e Literatura Portuguesa (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH29", nome: "Letras - L\u00edngua e Literatura Japonesa (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH32", nome: "Letras - L\u00edngua Brasileira de Sinais\/LIBRAS", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FS02", nome: "Medicina (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FS03", nome: "Odontologia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE06-FP", nome: "Psicologia - Forma\u00e7\u00e3o do Psic\u00f3logo (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT01", nome: "Engenharia Civil (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT02-E", nome: "Engenharia El\u00e9trica - Eletr\u00f4nica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT02-ET", nome: "Engenharia El\u00e9trica - Eletrot\u00e9cnica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT02-T", nome: "Engenharia El\u00e9trica - Telecomunica\u00e7\u00f5es (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT05", nome: "Engenharia da Computa\u00e7\u00e3o (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT06", nome: "Engenharia de Produ\u00e7\u00e3o (Vesp.\/Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT07", nome: "Design (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT08", nome: "Engenharia de Materiais (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT09", nome: "Engenharia Mec\u00e2nica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT10", nome: "Arquitetura e Urbanismo (Vesp.\/Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT11", nome: "Engenharia de Petr\u00f3leo e G\u00e1s (Vesp.\/Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FT12", nome: "Engenharia Qu\u00edmica (Vesp.\/Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB01-B", nome: "Ci\u00eancias Biol\u00f3gicas - Bacharelado (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB01-L", nome: "Ci\u00eancias Biol\u00f3gicas - Licenciatura (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB05", nome: "Ci\u00eancias Naturais (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB09", nome: "Biotecnologia (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB14", nome: "Ci\u00eancias Naturais (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IB15", nome: "Ci\u00eancias Biol\u00f3gicas (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE01", nome: "Estat\u00edstica (Vesp\/Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE02", nome: "Geologia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE03-L", nome: "Matem\u00e1tica - Licenciatura (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE07", nome: "Matem\u00e1tica - Licenciatura (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE09", nome: "Qu\u00edmica - Licenciatura (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE10", nome: "F\u00edsica - Licenciatura (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE11", nome: "Qu\u00edmica - Bacharelado (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE13", nome: "F\u00edsica - Licenciatura (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE14", nome: "F\u00edsica - Bacharelado (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IE16", nome: "Matem\u00e1tica Aplicada (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH06", nome: "Servi\u00e7o Social (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH07-B", nome: "Geografia - Bacharelado (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH07-L", nome: "Geografia - Licenciatura (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH08", nome: "Hist\u00f3ria (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH10", nome: "Ci\u00eancias Sociais - Bacharelado (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH14", nome: "Filosofia (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH20", nome: "Hist\u00f3ria (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH22", nome: "Geografia - Licenciatura (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH26", nome: "Servi\u00e7o Social (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH33", nome: "Licenciatura Ind\u00edgena Pol\u00edticas Educacionais e Desenvolvimento Sustent\u00e1vel - Baniwa", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH34", nome: "Licenciatura Ind\u00edgena Pol\u00edticas Educacionais e Desenvolvimento Sustent\u00e1vel - Tukano", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH35", nome: "Licenciatura Ind\u00edgena Pol\u00edticas Educacionais e Desenvolvimento Sustent\u00e1vel - Nheengatu", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH36", nome: "Licenciatura Ind\u00edgena Pol\u00edticas Educacionais e Desenvolvimento Sustent\u00e1vel - Yanomami", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IH37", nome: "Licenciatura Ind\u00edgena Pol\u00edticas Educacionais e Desenvolvimento Sustent\u00e1vel - Sater\u00e9-Maw\u00e9", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE02", nome: "Pedagogia (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE03", nome: "Pedagogia (Vespertino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE07", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Humanas e Sociais - Borba", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE08", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Letras e Artes - Borba", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE09", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Exatas e Biol\u00f3gicas - Borba", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE10", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Humanas e Sociais - Mau\u00e9s", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE11", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Letras e Artes - Mau\u00e9s", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE12", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Exatas e Biol\u00f3gicas - Mau\u00e9s", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE13", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Humanas e Sociais - M. Solim\u00f5es", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE14", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Letras e Artes - M. Solim\u00f5es", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE15", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Exatas e Biol\u00f3gicas - M. Solim\u00f5es", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE16", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Letras e Artes - Alto Rio Negro", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE17", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Letras e Artes - Alto Solim\u00f5es", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE18", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Exatas e Biol\u00f3gicas - Alto Rio Negro", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE19", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Humanas e Sociais - Alto Rio Negro", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE20", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Exatas e Biol\u00f3gicas - Alto Solim\u00f5es", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE21", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Humanas e Sociais - Alto Solim\u00f5es", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE22", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Humanas e Sociais - L\u00e1brea", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE23", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Exatas e Biol\u00f3gicas - L\u00e1brea", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE24", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Letras e Artes - L\u00e1brea", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "FE25", nome: "Forma\u00e7\u00e3o de Professores Ind\u00edgenas - Humanas e Sociais - Manicor\u00e9", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IN01", nome: "Administra\u00e7\u00e3o (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IN02", nome: "Pedagogia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IN03", nome: "Antropologia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IN05", nome: "Letras - L\u00edngua e Literatura Portuguesa e L\u00edngua e Literatura Espanhola (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IN06", nome: "Ci\u00eancias - Biologia e Qu\u00edmica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IN07", nome: "Ci\u00eancias Agr\u00e1rias e do Ambiente (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IS01", nome: "Nutri\u00e7\u00e3o (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IS02", nome: "Biotecnologia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IS03", nome: "Fisioterapia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IS04", nome: "Enfermagem (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IS05", nome: "Ci\u00eancias - Matem\u00e1tica e F\u00edsica (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IS06", nome: "Ci\u00eancias - Biologia e Qu\u00edmica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IS07", nome: "Medicina (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IA01", nome: "Agronomia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IA02", nome: "Engenharia Ambiental (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IA03", nome: "Ci\u00eancias - Biologia e Qu\u00edmica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IA04", nome: "Pedagogia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IA05", nome: "Letras - L\u00edngua Portuguesa e L\u00edngua Inglesa (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IA06", nome: "Ci\u00eancias - Matem\u00e1tica e F\u00edsica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT01", nome: "Sistemas de Informa\u00e7\u00e3o (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT02", nome: "Farm\u00e1cia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT03", nome: "Engenharia de Produ\u00e7\u00e3o (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT04", nome: "Ci\u00eancias - Matem\u00e1tica e F\u00edsica (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT05", nome: "Ci\u00eancias - Qu\u00edmica e Biologia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT06", nome: "Qu\u00edmica Industrial (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT16", nome: "Engenharia de Software (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT17", nome: "Engenharia Sanit\u00e1ria (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IT18", nome: "Agronomia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IP01", nome: "Administra\u00e7\u00e3o (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IP02", nome: "Comunica\u00e7\u00e3o Social - Jornalismo (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IP03", nome: "Educa\u00e7\u00e3o F\u00edsica (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IP04", nome: "Pedagogia (Matutino)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IP05", nome: "Servi\u00e7o Social (Diurno", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IP06", nome: "Zootecnia (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      // { sigla: "IP07", nome: "Artes Visuais (Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      { sigla: "IE08", nome: "Ci\u00eancia da Computa\u00e7\u00e3o (Diurno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
      { sigla: "IE17", nome: "Engenharia de Software (Vesp\/Noturno)", id_area: 1, created_at: new Date(new Date() + "+0"), updated_at: new Date(new Date() + "+0") },
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('curso', {}, {});
  }
};
