module.exports = {
	ajuda: require(__dirname + "/../app/models/ajuda"), 
	area: require(__dirname + "/../app/models/area"), 
	cargo: require(__dirname + "/../app/models/cargo"), 
	categoria: require(__dirname + "/../app/models/categoria"), 
	curso: require(__dirname + "/../app/models/curso"), 
	denuncia: require(__dirname + "/../app/models/denuncia"), 
	dificuldade: require(__dirname + "/../app/models/dificuldade"), 
	disciplina: require(__dirname + "/../app/models/disciplina"), 
	disciplina_curso: require(__dirname + "/../app/models/disciplina_curso"), 
	disponibilidade: require(__dirname + "/../app/models/disponibilidade"), 
	especialidade: require(__dirname + "/../app/models/especialidade"), 
	monitor: require(__dirname + "/../app/models/monitor"), 
	mudar_senha: require(__dirname + "/../app/models/mudar_senha"), 
	usuario: require(__dirname + "/../app/models/usuario"), 
}